# Generated by Django 2.2.5 on 2019-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=50)),
                ('discount_value', models.IntegerField()),
                ('discount_type', models.CharField(max_length=3)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('usage_number', models.IntegerField()),
                ('max_usage', models.IntegerField(default=3)),
            ],
        ),
    ]
